language: shell
os: linux
dist: bionic

services:
  - docker

env:
  global:
    boost_version: 1.65.0
  jobs:
    - configuration=Debug   platform=x86
    - configuration=Release platform=x86
    - configuration=Debug   platform=x64
    - configuration=Release platform=x64

# MinGW-w64 7.0 or higher is required, which is only available on Focal.
# I tried building it manually, but failed miserably, which is why I opted for
# a Docker build.
script: >-
    docker-compose -f .travis/docker-compose.yml
    build
    --build-arg boost_version="$boost_version"
    --build-arg platform="$platform"
    --build-arg configuration="$configuration"
    mingw_build

jobs:
  fast_finish: true

  include:
    - name: Run clang-format
      if: branch = master
      addons:
        apt:
          update: true
          packages:
            - clang-format-9
          sources:
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
      script: ./cmake/tools/clang-format.py --clang-format clang-format-9
