version: '{build}'
image: 'Visual Studio 2017'

branches:
  only:
    - master

environment:
  appveyor_boost_version: 1.69.0

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

build_script:
  - ps: .\.appveyor\build.ps1
