version: '{build}'

image:
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019

environment:
  python_exe: C:\Python36-x64\python.exe
  install_dir: C:\Projects\install\pdb-repo

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

install:
  - git submodule update --init --recursive

build_script:
  - '"%python_exe%" cmake\ci\build_appveyor.py --install "%install_dir%" -- -D "BOOST_ROOT=%appveyor_boost_root%" -D "BOOST_LIBRARYDIR=%appveyor_boost_librarydir%"'

after_build:
  - 7z.exe a "%APPVEYOR_PROJECT_NAME%-%PLATFORM%-%CONFIGURATION%.zip" "%install_dir%"
  - appveyor.exe PushArtifact "%APPVEYOR_PROJECT_NAME%-%PLATFORM%-%CONFIGURATION%.zip"

for:
# Only build Release builds on master to speed things up:
- branches:
    except:
      - master
  configuration:
    - Debug

- matrix:
    only:
      - image: Visual Studio 2015
        platform: Win32
  environment:
    appveyor_boost_root: C:\Libraries\boost_1_62_0
    appveyor_boost_librarydir: C:\Libraries\boost_1_62_0\lib32-msvc-14.0
- matrix:
    only:
      - image: Visual Studio 2015
        platform: x64
  environment:
    appveyor_boost_root: C:\Libraries\boost_1_62_0
    appveyor_boost_librarydir: C:\Libraries\boost_1_62_0\lib64-msvc-14.0
- matrix:
    only:
      - image: Visual Studio 2017
        platform: Win32
  environment:
    appveyor_boost_root: C:\Libraries\boost_1_69_0
    appveyor_boost_librarydir: C:\Libraries\boost_1_69_0\lib32-msvc-14.1
- matrix:
    only:
      - image: Visual Studio 2017
        platform: x64
  environment:
    appveyor_boost_root: C:\Libraries\boost_1_69_0
    appveyor_boost_librarydir: C:\Libraries\boost_1_69_0\lib64-msvc-14.1
- matrix:
    only:
      - image: Visual Studio 2019
        platform: Win32
  environment:
    appveyor_boost_root: C:\Libraries\boost_1_71_0
    appveyor_boost_librarydir: C:\Libraries\boost_1_71_0\lib32-msvc-14.2
- matrix:
    only:
      - image: Visual Studio 2019
        platform: x64
  environment:
    appveyor_boost_root: C:\Libraries\boost_1_71_0
    appveyor_boost_librarydir: C:\Libraries\boost_1_71_0\lib64-msvc-14.2
